# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    booking.listener:
        class: AppBundle\EventListener\BookingListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
    order.listener:
        class: AppBundle\EventListener\OrderListener
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
    customer.listener:
        class: AppBundle\EventListener\CustomerListener
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
    app.data.manager:
        class: AppBundle\Manager\DataManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@mailer'
            - '@templating'
            - '@form.factory'
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
