<?php

namespace AppBundle\Entity;

/**
 * BoatPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoatPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
